# Generated by Django 3.0.3 on 2020-03-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200311_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
